# Environment variables prefixed with _ are set as substitutions in the Cloud Build Trigger definition.
steps:
  # Build controller
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller", "."]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller:${TAG_NAME:-$SHORT_SHA}",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller:${TAG_NAME:-$SHORT_SHA}"]

  # Build controller-spa
  - name: "oven/bun:1.2.1"
    dir: "apps/controller-spa"
    entrypoint: bun
    args: ["install", "--production"]

  - name: "oven/bun:1.2.1"
    dir: "apps/controller-spa"
    entrypoint: bun
    env:
      - "CONTROLLER_API_URL=https://${_DOMAIN}/api"
      - "VITE_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}"
    args: ["run", "build"]

  # Push build files to Google Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "cp", "-r", "apps/controller-spa/dist/*", "gs://${_FRONTEND_BUCKET}"]

  # Deploy controller to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_CLOUD_RUN_SERVICE_NAME}"
      - "--image"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller:${TAG_NAME:-$SHORT_SHA}"
      - "--region"
      - "$LOCATION"

images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller"
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/rejot/controller:${TAG_NAME:-$SHORT_SHA}"
options:
  logging: CLOUD_LOGGING_ONLY
