services:
  postgres_source:
    image: postgres:17
    container_name: postgres_source
    ports:
      - "5433:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_sink:
    image: postgres:17
    container_name: postgres_sink
    ports:
      - "5434:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bun-published:
    image: oven/bun:1.2.6
    container_name: bun-published
    environment:
      REJOT_DB_1: "postgres://postgres:postgres@postgres_source:5432/postgres"
      REJOT_DB_2: "postgres://postgres:postgres@postgres_sink:5432/postgres"
    depends_on:
      postgres_source:
        condition: service_healthy
      postgres_sink:
        condition: service_healthy

  bun-local:
    image: oven/bun:1.2.6
    container_name: bun-local
    volumes:
      - ../..:/opt
      - ./rejot-cli.sh:/usr/local/bin/rejot-cli
    environment:
      REJOT_DB_1: "postgres://postgres:postgres@postgres_source:5432/postgres"
      REJOT_DB_2: "postgres://postgres:postgres@postgres_sink:5432/postgres"
    depends_on:
      postgres_source:
        condition: service_healthy
      postgres_sink:
        condition: service_healthy
