name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

  check-prettier:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

      - name: Check formatting
        run: bun run format:check

  check-eslint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

      - name: Run linter
        run: bun run lint

  typecheck-controller:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

      - name: Type check controller
        working-directory: apps/controller
        run: bun check

  typecheck-controller-spa:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

      - name: Type check controller-spa
        working-directory: apps/controller-spa
        run: bun check

  typecheck-api-interface:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

      - name: Type check api-interface-controller
        working-directory: packages/api-interface-controller
        run: bun check

  test-postgres:
    needs: install
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lock') }}

      - name: Create Database Schema
        working-directory: apps/controller
        run: bunx drizzle-kit --config=_ci/ci-test-drizzle.config.ts migrate

      - name: Generate and check for unstaged migrations
        working-directory: apps/controller
        run: |
          bunx drizzle-kit --config=_ci/ci-test-drizzle.config.ts generate
          if ! git diff --quiet drizzle/; then
            echo "Error: Found unstaged migration files in apps/controller/drizzle"
            echo "New/modified migration files:"
            git status drizzle/
            echo "Contents of modified SQL files:"
            (git ls-files -m drizzle/ && git ls-files --others --exclude-standard drizzle/) | grep '\.sql$' | while read file; do
              echo -e "\n=== $file ===\n"
              cat "$file"
            done
            exit 1
          fi

      - name: Run database tests
        working-directory: apps/controller
        env:
          REJOT_CONTROLLER_CONFIG_PATH: ./_ci/ci-test-config.json
        run: bun test
