name: Publish NPM packages

on:
  push:
    tags: ["v*"]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        # NOTE! Also add to verify-installation job! (yaml anchors not supported in github actions yet)
        path:
          - packages/adapter-postgres
          - packages/contract
          - packages/sync
          - packages/sqlparser
          - packages/contract-tools
          - apps/rejot-cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Publish package
        working-directory: ${{ matrix.path }}
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

  verify-installation:
    needs: publish-npm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - "@rejot-dev/adapter-postgres"
          - "@rejot-dev/contract"
          - "@rejot-dev/sync"
          - "@rejot-dev/sqlparser"
          - "@rejot-dev/cli"
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8

      - name: Create test directory
        run: mkdir test-install && cd test-install

      - name: Install published package
        working-directory: ./test-install
        run: bun install ${{ matrix.package }}@${GITHUB_REF_NAME#v}
