name: Publish NPM packages

on:
  push:
    tags: ["v*"]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package:
          - path: packages/adapter-postgres
            name: "@rejot-dev/adapter-postgres"
          - path: packages/contract
            name: "@rejot-dev/contract"
          - path: packages/sync
            name: "@rejot-dev/sync"
          - path: packages/sqlparser
            name: "@rejot-dev/sqlparser"
          - path: apps/rejot-cli
            name: "@rejot-dev/cli"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Publish package
        working-directory: ${{ matrix.package.path }}
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
