name: Python
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-rejot-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build rejot-python-package
        working-directory: python
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade build
          pip install .
          python -m build

      - name: Check Types
        working-directory: python
        run: |
          source venv/bin/activate
          pip install mypy==1.15.0
          mypy src

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: python/dist/

  publish-rejot-python-package:
    runs-on: ubuntu-latest
    needs: build-rejot-python-package
    environment:
      name: pypi
      url: https://pypi.org/p/rejot-contract
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install twine
        working-directory: python
        run: |
          source venv/bin/activate
          pip install twine

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
